apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    tekton.dev/tags: kubevirt
    pipeline.openshift.io/started-by: cluster-admin
    tekton.dev/categories: Automation
    artifacthub.io/provider: KubeVirt
    tekton.dev/platforms: linux/amd64
    tekton.dev/pipelines.minVersion: 0.43.0
    artifacthub.io/category: integration-delivery
    artifacthub.io/recommendations: |
      - url: https://kubevirt.io/
    artifacthub.io/maintainers: |
      - name: KubeVirt Tekton tasks maintainers
        email: kubevirt-tekton-tasks@redhat.com
    tekton.dev/displayName: KubeVirt Windows UEFI installer
  resourceVersion: '6302420'
  name: windows-efi-installer-jqfdw0
  uid: 630c5b72-e573-4b1e-bacd-31b358912df4
  creationTimestamp: '2024-03-22T16:13:09Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:tekton.dev/platforms': {}
            'f:artifacthub.io/category': {}
            .: {}
            'f:artifacthub.io/recommendations': {}
            'f:artifacthub.io/maintainers': {}
            'f:tekton.dev/displayName': {}
            'f:tekton.dev/tags': {}
            'f:tekton.dev/categories': {}
            'f:artifacthub.io/provider': {}
            'f:tekton.dev/pipelines.minVersion': {}
            'f:pipeline.openshift.io/started-by': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/version': {}
            'f:tekton.dev/pipeline': {}
        'f:spec':
          .: {}
          'f:params': {}
          'f:pipelineRef':
            .: {}
            'f:name': {}
          'f:status': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2024-03-22T16:13:09Z'
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"chains.tekton.dev/pipelinerun"': {}
      manager: openshift-pipelines-chains-controller
      operation: Update
      time: '2024-03-22T16:13:09Z'
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:childReferences': {}
          'f:conditions': {}
          'f:pipelineSpec':
            .: {}
            'f:description': {}
            'f:finally': {}
            'f:params': {}
            'f:results': {}
            'f:tasks': {}
          'f:provenance':
            .: {}
            'f:featureFlags':
              'f:ScopeWhenExpressionsToTask': {}
              'f:SetSecurityContext': {}
              'f:DisableCredsInit': {}
              'f:DisableAffinityAssistant': {}
              'f:EnableKeepPodOnCancel': {}
              'f:VerificationNoMatchPolicy': {}
              'f:RunningInEnvWithInjectedSidecars': {}
              'f:EnableCELInWhenExpression': {}
              'f:EnableTektonOCIBundles': {}
              .: {}
              'f:MaxResultSize': {}
              'f:AwaitSidecarReadiness': {}
              'f:EnableProvenanceInStatus': {}
              'f:EnableParamEnum': {}
              'f:Coschedule': {}
              'f:ResultExtractionMethod': {}
              'f:EnableStepActions': {}
              'f:EnableAPIFields': {}
              'f:RequireGitSSHSecretKnownHosts': {}
              'f:EnforceNonfalsifiability': {}
              'f:SendCloudEventsForRuns': {}
          'f:startTime': {}
      manager: openshift-pipelines-controller
      operation: Update
      subresource: status
      time: '2024-03-22T16:13:17Z'
  namespace: build-winvm
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    app.kubernetes.io/version: v0.19.0
    tekton.dev/pipeline: windows-efi-installer
spec:
  params:
    - name: winImageDownloadURL
      value: 'https://go.microsoft.com/fwlink/p/?LinkID=2195280&clcid=0x409&culture=en-us&country=US'
    - name: instanceTypeName
      value: u1.large
    - name: instanceTypeKind
      value: VirtualMachineClusterInstancetype
    - name: preferenceName
      value: windows.2k22
    - name: virtualMachinePreferenceKind
      value: VirtualMachineClusterPreference
    - name: autounattendConfigMapName
      value: windows2k22-autounattend
    - name: virtioContainerDiskName
      value: 'quay.io/kubevirt/virtio-container-disk:v1.2.0'
    - name: baseDvName
      value: win2k22
    - name: baseDvNamespace
      value: openshift-virtualization-os-images
    - name: isoDVName
      value: win2k22
  pipelineRef:
    name: windows-efi-installer
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s